import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedStep1Wheneveryouwanttoproveyouridentityaskthesecuritype.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedProveyourIdentityWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget58.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedStep4Aftersuccessfulverificationourappwillsendyouthever.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedAadharWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedGroup6610Widget7.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedGroup7872Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget56.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget60.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget57.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFormWidget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedInfoWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget55.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedPanWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget54.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedStep3YouhavetoscanthatQRandapopupwillaskyourphonenumber.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedQuickActionsWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedStep2WhenSecuritypersonentersyourphonenoauniquesecuredQ.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedRectangle2869Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedGroup6607Widget11.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen10widget/generated/GeneratedFrameWidget59.dart';

/* Frame Screen 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 449.0,
                child: GeneratedRectangle2869Widget3(),
              ),
              Positioned(
                left: 63.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 29.0,
                child: GeneratedProveyourIdentityWidget1(),
              ),
              Positioned(
                left: 157.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 45.68511962890625,
                height: 25.0,
                child: GeneratedGroup6610Widget7(),
              ),
              Positioned(
                left: 40.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedGroup6607Widget11(),
              ),
              Positioned(
                left: 40.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 11.59000015258789,
                height: 11.685999870300293,
                child: GeneratedFrameWidget54(),
              ),
              Positioned(
                left: 62.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 63.0,
                child:
                    GeneratedStep1Wheneveryouwanttoproveyouridentityaskthesecuritype(),
              ),
              Positioned(
                left: 40.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 11.59000015258789,
                height: 11.685999870300293,
                child: GeneratedFrameWidget55(),
              ),
              Positioned(
                left: 62.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 41.0,
                child:
                    GeneratedStep2WhenSecuritypersonentersyourphonenoauniquesecuredQ(),
              ),
              Positioned(
                left: 40.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 11.59000015258789,
                height: 11.685999870300293,
                child: GeneratedFrameWidget56(),
              ),
              Positioned(
                left: 62.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 82.0,
                child:
                    GeneratedStep3YouhavetoscanthatQRandapopupwillaskyourphonenumber(),
              ),
              Positioned(
                left: 40.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 11.59000015258789,
                height: 11.685999870300293,
                child: GeneratedFrameWidget57(),
              ),
              Positioned(
                left: 62.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 60.0,
                child:
                    GeneratedStep4Aftersuccessfulverificationourappwillsendyouthever(),
              ),
              Positioned(
                left: 28.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 70.0,
                child: GeneratedFrameWidget58(),
              ),
              Positioned(
                left: 186.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 70.0,
                child: GeneratedFrameWidget59(),
              ),
              Positioned(
                left: 107.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 70.0,
                child: GeneratedFrameWidget60(),
              ),
              Positioned(
                left: 264.4444580078125,
                top: 606.0,
                right: null,
                bottom: null,
                width: 67.5555419921875,
                height: 70.0,
                child: GeneratedGroup7872Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 30.0,
                child: GeneratedInfoWidget1(),
              ),
              Positioned(
                left: 112.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 30.0,
                child: GeneratedAadharWidget1(),
              ),
              Positioned(
                left: 197.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 30.0,
                child: GeneratedPanWidget1(),
              ),
              Positioned(
                left: 276.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 30.0,
                child: GeneratedFormWidget3(),
              ),
              Positioned(
                left: 28.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 22.0,
                child: GeneratedQuickActionsWidget1(),
              )
            ]),
      ),
    ));
  }
}
