import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen3widget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen3widget/generated/GeneratedStep3Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen3widget/generated/GeneratedGroup6606Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen3widget/generated/GeneratedAftersuccessfulscanOTPwillcomeonyourphonenumberentertha.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen3widget/generated/GeneratedLine1Widget4.dart';

/* Frame Screen 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 29.0,
                child: GeneratedStep3Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 72.0,
                child:
                    GeneratedAftersuccessfulscanOTPwillcomeonyourphonenumberentertha(),
              ),
              Positioned(
                left: 39.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 1.0,
                child: GeneratedLine1Widget4(),
              ),
              Positioned(
                left: 40.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 70.0,
                child: GeneratedGroup6606Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 315.20001220703125,
                child: GeneratedImage2Widget(),
              )
            ]),
      ),
    ));
  }
}
