import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/Generated0015secWidget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedGroup6607Widget5.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedFrameWidget22.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedRectangle2868Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedWejustsentyoua4digitcodeto919535728726ChangeNumberWidge3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedRectangle2867Widget4.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedVerificationWidget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedRectangle2865Widget4.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen16widget/generated/GeneratedRectangle2866Widget4.dart';

/* Frame Screen 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 114.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 32.0,
                child: GeneratedVerificationWidget3(),
              ),
              Positioned(
                left: 69.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 53.0,
                child:
                    GeneratedWejustsentyoua4digitcodeto919535728726ChangeNumberWidge3(),
              ),
              Positioned(
                left: 69.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 28.0,
                child: Generated0015secWidget3(),
              ),
              Positioned(
                left: 46.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedGroup6607Widget5(),
              ),
              Positioned(
                left: 51.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2865Widget4(),
              ),
              Positioned(
                left: 121.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2866Widget4(),
              ),
              Positioned(
                left: 191.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2867Widget4(),
              ),
              Positioned(
                left: 261.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2868Widget3(),
              ),
              Positioned(
                left: 34.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 14.244000434875488,
                height: 15.072999954223633,
                child: GeneratedFrameWidget22(),
              )
            ]),
      ),
    ));
  }
}
