description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
  code_fields: ^0.0.4
  timer_count_down: ^2.2.0
  url_launcher: ^6.0.3
  qr_flutter: ^4.0.0
  barcode_scan_fix: ^1.0.2
  cupertino_radio_choice: ^1.0.1+1
  group_button: ^3.2.0
  enhanced_drop_down: ^0.1.7+1
  find_dropdown: ^1.0.0
  passcode_screen: ^2.0.0
  
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Comfortaa"
      fonts: 
        - 
          asset: "fonts/Comfortaa-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Comfortaa-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Comfortaa-300.ttf"
          style: "normal"
          weight: 300
  uses-material-design: true
