import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedRectangle2865Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedGroup6608Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedSignuptogetstartedWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedEmailAddressWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedCreateAccountWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/Generated91Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedRectangle2864Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedAadharCardNumberOptionalWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedGroup6607Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedRectangle2866Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedEnterNameWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen5widget/generated/GeneratedRectangle2867Widget.dart';

/* Frame Screen 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center, overflow: Overflow.visible, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 82.0,
            top: 87.0,
            right: null,
            bottom: null,
            width: 198.0,
            height: 29.0,
            child: GeneratedCreateAccountWidget(),
          ),
          Positioned(
            left: 50.0,
            top: 118.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 27.0,
            child: GeneratedSignuptogetstartedWidget(),
          ),
          Positioned(
            left: 50.0,
            top: 629.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 54.0,
            child: GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget(),
          ),
          Positioned(
            left: 30.0,
            top: 173.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 50.0,
            child: TextFormField(
              decoration: InputDecoration(
                hintText: 'Enter your name',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(10),
                  ),
                ),
              ),
            ),
          ),
          // Positioned(
          //   left: 50.0,
          //   top: 185.0,
          //   right: null,
          //   bottom: null,
          //   width: 90.0,
          //   height: 28.0,
          //   child: GeneratedEnterNameWidget(),
          // ),
          Positioned(
            left: 77.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 207.0,
            height: 26.0,
            child: GeneratedGroup6608Widget(),
          ),
          Positioned(
            left: 30.0,
            top: 239.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 50.0,
            child: TextFormField(
              decoration: InputDecoration(
                contentPadding: EdgeInsets.fromLTRB(60, 0, 0, 0),
                hintText: 'Enter phone number',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(10),
                  ),
                ),
              ),
            ),
          ),
          Positioned(
            left: 50.0,
            top: 251.0,
            right: null,
            bottom: null,
            width: 27.0,
            height: 31.0,
            child: Generated91Widget(),
          ),
          Positioned(
            left: 30.0,
            top: 305.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 50.0,
            child: TextFormField(
              decoration: InputDecoration(
                hintText: 'Enter email address',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(10),
                  ),
                ),
              ),
            ),
          ),
          // Positioned(
          //   left: 50.0,
          //   top: 317.0,
          //   right: null,
          //   bottom: null,
          //   width: 106.0,
          //   height: 28.0,
          //   child: GeneratedEmailAddressWidget(),
          // ),
          Positioned(
            left: 30.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 50.0,
            child: TextFormField(
              decoration: InputDecoration(
                hintText: 'Aadhar Number (Optional)',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(10),
                  ),
                ),
              ),
            ),
          ),
          // Positioned(
          //   left: 50.0,
          //   top: 383.0,
          //   right: null,
          //   bottom: null,
          //   width: 236.0,
          //   height: 28.0,
          //   child: GeneratedAadharCardNumberOptionalWidget(),
          // ),
          Positioned(
            left: 80.5,
            top: 249.0,
            right: null,
            bottom: null,
            width: 0.0,
            height: 29.0,
            child: GeneratedVector1Widget(),
          ),
          Positioned(
            left: 40.0,
            top: 451.0,
            right: null,
            bottom: null,
            width: 280.0,
            height: 51.0,
            child: GeneratedGroup6607Widget(),
          ),
          // Positioned(
          //   left: 94.0,
          //   top: 251.0,
          //   right: null,
          //   bottom: null,
          //   width: 112.0,
          //   height: 28.0,
          //   child: GeneratedPhoneNumberWidget(),
          // )
        ]),
      ),
    ));
  }
}
