import 'package:flutter/material.dart';
import 'package:code_fields/code_fields.dart';
import 'package:timer_count_down/timer_count_down.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedRectangle2866Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedGroup6607Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedVerificationWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/Generated0015secWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedRectangle2868Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedRectangle2865Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedWejustsentyoua4digitcodeto919535728726ChangeNumberWidge.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen6widget/generated/GeneratedRectangle2867Widget1.dart';

/* Frame Screen 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 768.0,
          child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 32.0,
                child: GeneratedVerificationWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 53.0,
                child: GeneratedWejustsentyoua4digitcodeto919535728726ChangeNumberWidge(),
              ),
              Positioned(
                left: 170.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 28.0,
                child: Countdown(
                  seconds: 15,
                  build: (BuildContext context, double time) => Text(
                    time.toString(),
                    style: TextStyle(fontSize: 16),
                  ),
                  interval: Duration(milliseconds: 100),
                  onFinished: () {},
                ),
              ),
              Positioned(
                left: 50.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 54.0,
                child: GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedGroup6607Widget1(),
              ),
              Positioned(
                top: 239.0,
                right: null,
                bottom: null,
                child: CodeFields(
                  length: 4,
                  inputDecoration: InputDecoration(
                    filled: true,
                    fillColor: Colors.white,
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10.0),
                      borderSide: BorderSide(
                        color: Colors.black.withOpacity(0.2),
                      ),
                    ),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10.0),
                    ),
                  ),
                ),
              ),
              // Positioned(
              //   left: 115.0,
              //   top: 239.0,
              //   right: null,
              //   bottom: null,
              //   width: 60.0,
              //   height: 50.0,
              //   child: GeneratedRectangle2866Widget1(),
              // ),
              // Positioned(
              //   left: 185.0,
              //   top: 239.0,
              //   right: null,
              //   bottom: null,
              //   width: 60.0,
              //   height: 50.0,
              //   child: GeneratedRectangle2867Widget1(),
              // ),
              // Positioned(
              //   left: 255.0,
              //   top: 239.0,
              //   right: null,
              //   bottom: null,
              //   width: 60.0,
              //   height: 50.0,
              //   child: GeneratedRectangle2868Widget(),
              // )
            ],
          ),
        ),
      ),
    );
  }
}
