import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedFrameWidget38.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7881Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2868Widget5.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedAadharNumberWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedNationalityWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedEnterNameWidget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7883Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedResidentialStatusWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedFrameWidget34.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2864Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2873Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedEnterMotherNameWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7879Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedPath2597Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedPanNumberWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedDOBWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7886Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7884Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup6607Widget7.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2865Widget7.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGenderWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedFrameWidget35.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedFrameWidget36.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedVerifiedWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2869Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedFrameWidget37.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2875Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedOccupationWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedPersonalInfoWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedCityPlaceofbirthWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7880Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedMaritalStatusWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2870Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedFrameWidget33.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2874Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedEnterFatherNameWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedGroup7882Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2872Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedCountryofbirthWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2867Widget6.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedAdditionalDetailsWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen22widget/generated/GeneratedRectangle2866Widget6.dart';

/* Frame Screen 22
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen22Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1403.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1403.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 87.0,
                              right: null,
                              bottom: null,
                              width: 14.244000434875488,
                              height: 15.072999954223633,
                              child: GeneratedFrameWidget33(),
                            ),
                            Positioned(
                              left: 97.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 168.0,
                              height: 29.0,
                              child: GeneratedPersonalInfoWidget1(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 788.0,
                              right: null,
                              bottom: null,
                              width: 227.0,
                              height: 29.0,
                              child: GeneratedAdditionalDetailsWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2864Widget2(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 208.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 28.0,
                              child: GeneratedEnterNameWidget2(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 909.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2870Widget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 921.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 28.0,
                              child: GeneratedCityPlaceofbirthWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 1107.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2874Widget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 1119.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 28.0,
                              child: GeneratedAadharNumberWidget1(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 1119.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 31.0,
                              child: GeneratedVerifiedWidget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 1173.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2875Widget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 1185.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 28.0,
                              child: GeneratedPanNumberWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 630.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2868Widget5(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 28.0,
                              child: GeneratedResidentialStatusWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 262.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2865Widget7(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 328.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2866Widget6(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 28.0,
                              child: GeneratedEnterMotherNameWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 394.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2867Widget6(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 31.0,
                              child: GeneratedDOBWidget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 274.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 28.0,
                              child: GeneratedEnterFatherNameWidget1(),
                            ),
                            Positioned(
                              left: 294.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 19.0,
                              child: GeneratedFrameWidget34(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 25.0,
                              child: GeneratedGenderWidget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 20.0,
                              child: GeneratedGroup7879Widget1(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 20.0,
                              child: GeneratedGroup7880Widget1(),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 69.0,
                              height: 20.0,
                              child: GeneratedGroup7881Widget1(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 550.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 22.0,
                              child: GeneratedMaritalStatusWidget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 20.0,
                              child: GeneratedGroup7882Widget1(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 20.0,
                              child: GeneratedGroup7883Widget1(),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 69.0,
                              height: 20.0,
                              child: GeneratedGroup7884Widget1(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 653.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 5.0,
                              child: GeneratedFrameWidget35(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2869Widget2(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 708.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 31.0,
                              child: GeneratedOccupationWidget1(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 719.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 5.0,
                              child: GeneratedFrameWidget36(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 975.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2872Widget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 987.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 28.0,
                              child: GeneratedCountryofbirthWidget1(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 998.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 5.0,
                              child: GeneratedFrameWidget37(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 1041.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedRectangle2873Widget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 1053.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedNationalityWidget1(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 1064.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 5.0,
                              child: GeneratedFrameWidget38(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 1265.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 51.0,
                              child: GeneratedGroup6607Widget7(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 1125.0,
                              right: null,
                              bottom: null,
                              width: 12.512283325195312,
                              height: 13.52587890625,
                              child: GeneratedPath2597Widget2(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 845.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 50.0,
                              child: GeneratedGroup7886Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
