import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedGroup6610Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFormWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedPreviousscansWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFrameWidget7.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFrameWidget9.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedGroup7875Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedProveyourIdentityWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedQuickActionsWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFrameWidget5.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFrameWidget11.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedGroup6607Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFrameWidget6.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedGroup7876Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedRectangle2869Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedFrameWidget8.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedGroup7874Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedPanWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedAadharWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen9widget/generated/GeneratedGroup7877Widget.dart';

/* Frame Screen 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 768.0,
          child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 70.0,
                child: GeneratedFrameWidget5(),
              ),
              Positioned(
                left: 182.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 70.0,
                child: GeneratedFrameWidget6(),
              ),
              Positioned(
                left: 105.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 70.0,
                child: GeneratedFrameWidget7(),
              ),
              Positioned(
                left: 259.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 70.0,
                child: GeneratedFrameWidget8(),
              ),
              Positioned(
                left: 39.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 30.0,
                child: GeneratedInfoWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 40.0,
                child: GeneratedGroup7874Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 30.0,
                child: GeneratedAadharWidget(),
              ),
              Positioned(
                left: 193.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 30.0,
                child: GeneratedPanWidget(),
              ),
              Positioned(
                left: 270.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 30.0,
                child: GeneratedFormWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedFrameWidget9(),
              ),
              Positioned(
                left: 240.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 19.0,
                child: GeneratedGroup7875Widget(),
              ),
              Positioned(
                left: 83.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 40.0,
                child: GeneratedGroup7876Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedFrameWidget11(),
              ),
              Positioned(
                left: 240.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 19.0,
                child: GeneratedGroup7877Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 155.0,
                child: GeneratedRectangle2869Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 29.0,
                child: GeneratedProveyourIdentityWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 97.68511962890625,
                height: 25.0,
                child: GeneratedGroup6610Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedGroup6607Widget3(),
              ),
              Positioned(
                left: 28.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 22.0,
                child: GeneratedQuickActionsWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 22.0,
                child: GeneratedPreviousscansWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 1.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 88.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              )
            ],
          ),
        ),
      ),
    );
  }
}
