import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedWejustsentyoua4digitcodeto919535728726ChangeNumberWidge1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedRectangle2866Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedGroup6607Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedRectangle2868Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/Generated0015secWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedRectangle2865Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedVerificationWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen8widget/generated/GeneratedRectangle2867Widget2.dart';

/* Frame Screen 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 32.0,
                child: GeneratedVerificationWidget1(),
              ),
              Positioned(
                left: 63.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 53.0,
                child:
                    GeneratedWejustsentyoua4digitcodeto919535728726ChangeNumberWidge1(),
              ),
              Positioned(
                left: 63.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 28.0,
                child: Generated0015secWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 54.0,
                child:
                    GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedGroup6607Widget2(),
              ),
              Positioned(
                left: 45.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2865Widget2(),
              ),
              Positioned(
                left: 115.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2866Widget2(),
              ),
              Positioned(
                left: 185.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2867Widget2(),
              ),
              Positioned(
                left: 255.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 50.0,
                child: GeneratedRectangle2868Widget1(),
              )
            ]),
      ),
    ));
  }
}
