import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedYouraccountwillbeopenoncetheauthorisedpersonverifythede.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedNamePrathamGoelMobileNo7082346975Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedFrameWidget49.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedGroup6607Widget10.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedGroup6610Widget6.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedRectangle2913Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen19widget/generated/GeneratedFrameWidget48.dart';

/* Frame Screen 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 178.0,
                child: GeneratedFrameWidget48(),
              ),
              Positioned(
                left: 28.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 14.244000434875488,
                height: 15.072999954223633,
                child: GeneratedFrameWidget49(),
              ),
              Positioned(
                left: 28.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 159.0,
                child: GeneratedRectangle2913Widget2(),
              ),
              Positioned(
                left: 81.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 46.0,
                child: GeneratedNamePrathamGoelMobileNo7082346975Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 51.0,
                child: GeneratedGroup6607Widget10(),
              ),
              Positioned(
                left: 75.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 209.14500427246094,
                height: 25.0,
                child: GeneratedGroup6610Widget6(),
              ),
              Positioned(
                left: 50.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 77.0,
                child:
                    GeneratedYouraccountwillbeopenoncetheauthorisedpersonverifythede(),
              )
            ]),
      ),
    ));
  }
}
