import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen17widget/generated/GeneratedFrameWidget25.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen17widget/generated/GeneratedRequestingforBankaccountformWidget.dart';

/* Frame Screen 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedScreen18Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 768.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 62.0,
                  top: 311.0,
                  right: null,
                  bottom: null,
                  width: 239.0,
                  height: 95.0,
                  child: GeneratedRequestingforBankaccountformWidget(),
                ),
                Positioned(
                  left: 143.0,
                  top: 198.0,
                  right: null,
                  bottom: null,
                  width: 76.0,
                  height: 76.0,
                  child: GeneratedFrameWidget25(),
                )
              ]),
        ),
      ),
    ));
  }
}
