import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedGroup6607Widget12.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedGroup6608Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedPhoneNumberWidget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/Generated91Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedVector1Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedWelcomebackWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedEnteryourmobilenumbertocontinueWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen7widget/generated/GeneratedRectangle2865Widget9.dart';

/* Frame Screen 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 768.0,
          child: Stack(fit: StackFit.expand, alignment: Alignment.center, overflow: Overflow.visible, children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 88.0,
              top: 87.0,
              right: null,
              bottom: null,
              width: 187.0,
              height: 29.0,
              child: GeneratedWelcomebackWidget(),
            ),
            Positioned(
              left: 50.0,
              top: 118.0,
              right: null,
              bottom: null,
              width: 262.0,
              height: 27.0,
              child: GeneratedEnteryourmobilenumbertocontinueWidget(),
            ),
            Positioned(
              left: 50.0,
              top: 629.0,
              right: null,
              bottom: null,
              width: 262.0,
              height: 54.0,
              child: GeneratedBysigninintoidenttyouAgreetoourTermsPrivacyPolicyWidget3(),
            ),
            Positioned(
              left: 59.0,
              top: 410.0,
              right: null,
              bottom: null,
              width: 243.0,
              height: 26.0,
              child: GeneratedGroup6608Widget1(),
            ),
            Positioned(
              left: 30.0,
              top: 239.0,
              right: null,
              bottom: null,
              width: 300.0,
              height: 50.0,
              child: TextFormField(
                decoration: InputDecoration(
                  contentPadding: EdgeInsets.fromLTRB(60, 0, 0, 0),
                  hintText: 'Enter phone number',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.all(
                      Radius.circular(10),
                    ),
                  ),
                ),
              ),
            ),
            Positioned(
              left: 50.0,
              top: 251.0,
              right: null,
              bottom: null,
              width: 27.0,
              height: 31.0,
              child: Generated91Widget3(),
            ),
            Positioned(
              left: 85.5,
              top: 249.0,
              right: null,
              bottom: null,
              width: 0.0,
              height: 29.0,
              child: GeneratedVector1Widget3(),
            ),
            Positioned(
              left: 40.0,
              top: 339.0,
              right: null,
              bottom: null,
              width: 280.0,
              height: 51.0,
              child: GeneratedGroup6607Widget12(),
            ),
            // Positioned(
            //   left: 94.0,
            //   top: 251.0,
            //   right: null,
            //   bottom: null,
            //   width: 112.0,
            //   height: 28.0,
            //   child: TextFormField(
            //     decoration: InputDecoration(
            //       contentPadding: EdgeInsets.fromLTRB(60, 0, 0, 0),
            //       hintText: 'Enter phone number',
            //       border: OutlineInputBorder(
            //         borderRadius: BorderRadius.all(
            //           Radius.circular(10),
            //         ),
            //       ),
            //     ),
            //   ),
            // )
          ]),
        ),
      ),
    );
  }
}
