import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedFrameWidget41.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedGroup6610Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedAsamehasbeensenttotheAuthorisedpersonWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedFrameWidget40.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedAadharCard1111111111111111NamePrathamGoelMobileNo708234.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedRectangle2913Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen14widget/generated/GeneratedGroup6607Widget8.dart';

/* Frame Screen 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 178.0,
                child: GeneratedFrameWidget40(),
              ),
              Positioned(
                left: 28.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 14.244000434875488,
                height: 15.072999954223633,
                child: GeneratedFrameWidget41(),
              ),
              Positioned(
                left: 28.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 181.0,
                child: GeneratedRectangle2913Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 68.0,
                child:
                    GeneratedAadharCard1111111111111111NamePrathamGoelMobileNo708234(),
              ),
              Positioned(
                left: 58.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 51.0,
                child: GeneratedGroup6607Widget8(),
              ),
              Positioned(
                left: 75.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 209.14500427246094,
                height: 25.0,
                child: GeneratedGroup6610Widget2(),
              ),
              Positioned(
                left: 50.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 54.0,
                child: GeneratedAsamehasbeensenttotheAuthorisedpersonWidget(),
              )
            ]),
      ),
    ));
  }
}
