import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen2widget/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen2widget/generated/GeneratedGroup6606Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen2widget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen2widget/generated/GeneratedScantheQRcodeontheMobileAppWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen2widget/generated/GeneratedStep2Widget.dart';

/* Frame Screen 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 29.0,
                child: GeneratedStep2Widget(),
              ),
              Positioned(
                left: 81.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 72.0,
                child: GeneratedScantheQRcodeontheMobileAppWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 1.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 70.0,
                child: GeneratedGroup6606Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 315.0,
                child: GeneratedImage1Widget(),
              )
            ]),
      ),
    ));
  }
}
