import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7882Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2874Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7886Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedCountryofbirthWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2872Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedOccupationWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedEnterFatherNameWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2869Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2875Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7879Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedResidentialStatusWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGenderWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedPanNumberWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedFrameWidget28.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7883Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2865Widget5.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedPersonalInfoWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedMaritalStatusWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2867Widget5.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedFrameWidget29.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedEnterMotherNameWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedCityPlaceofbirthWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7884Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedAdditionalDetailsWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup6607Widget6.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedFrameWidget31.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7881Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedFrameWidget26.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedAadharNumberWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2864Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2868Widget4.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedGroup7880Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2870Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedEnterNameWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2873Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedRectangle2866Widget5.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedFrameWidget30.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedFrameWidget27.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedEverifyWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedDOBWidget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen18widget/generated/GeneratedNationalityWidget.dart';
import 'package:group_button/group_button.dart';
import 'package:enhanced_drop_down/enhanced_drop_down.dart';
import 'package:find_dropdown/find_dropdown.dart';

/* Frame Screen 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen18Widget extends StatefulWidget {
  @override
  _GeneratedScreen18WidgetState createState() => _GeneratedScreen18WidgetState();
}

class _GeneratedScreen18WidgetState extends State<GeneratedScreen18Widget> {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1403.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1403.0,
                      child: Stack(fit: StackFit.expand, alignment: Alignment.center, overflow: Overflow.visible, children: [
                        ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Container(
                            color: Color.fromARGB(255, 255, 255, 255),
                          ),
                        ),
                        Positioned(
                          left: 28.0,
                          top: 87.0,
                          right: null,
                          bottom: null,
                          width: 14.244000434875488,
                          height: 15.072999954223633,
                          child: GeneratedFrameWidget26(),
                        ),
                        Positioned(
                          left: 97.0,
                          top: 139.0,
                          right: null,
                          bottom: null,
                          width: 168.0,
                          height: 29.0,
                          child: GeneratedPersonalInfoWidget(),
                        ),
                        Positioned(
                          left: 68.0,
                          top: 788.0,
                          right: null,
                          bottom: null,
                          width: 227.0,
                          height: 29.0,
                          child: GeneratedAdditionalDetailsWidget(),
                        ),
                        Positioned(
                          left: 30.0,
                          top: 196.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'Enter your name',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 208.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 90.0,
                        //   height: 28.0,
                        //   child: GeneratedEnterNameWidget1(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 909.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'City/Place of birth*',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 921.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 140.0,
                        //   height: 28.0,
                        //   child: GeneratedCityPlaceofbirthWidget(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 1107.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'Aadhar Number',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 1119.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 120.0,
                        //   height: 28.0,
                        //   child: GeneratedAadharNumberWidget(),
                        // ),
                        // Positioned(
                        //   left: 256.0,
                        //   top: 1119.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 59.0,
                        //   height: 31.0,
                        //   child: GeneratedEverifyWidget(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 1173.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'Pan Number',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 1185.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 93.0,
                        //   height: 28.0,
                        //   child: GeneratedPanNumberWidget(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 630.0,
                          right: null,
                          bottom: null,
                          width: 300,
                          child: FindDropdown(
                            items: [
                              "Occupation",
                              "Student",
                              "Employed",
                              "UnEmployed"
                            ],
                            label: "",
                            onChanged: (String item) => print(item),
                            selectedItem: "Occupation",
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 642.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 134.0,
                        //   height: 28.0,
                        //   child: GeneratedResidentialStatusWidget(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 262.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'Enter your father name',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 30.0,
                          top: 328.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'Enter your mother name',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 340.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 147.0,
                        //   height: 28.0,
                        //   child: GeneratedEnterMotherNameWidget(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 394.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: TextFormField(
                            decoration: InputDecoration(
                              hintText: 'dd/mm/yyyy',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.all(
                                  Radius.circular(10),
                                ),
                              ),
                            ),
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 406.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 46.0,
                        //   height: 31.0,
                        //   child: GeneratedDOBWidget(),
                        // ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 274.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 142.0,
                        //   height: 28.0,
                        //   child: GeneratedEnterFatherNameWidget(),
                        // ),
                        Positioned(
                          left: 294.0,
                          top: 410.0,
                          right: null,
                          bottom: null,
                          width: 16.0,
                          height: 19.0,
                          child: GeneratedFrameWidget27(),
                        ),
                        Positioned(
                          left: 32.0,
                          top: 470.0,
                          right: null,
                          bottom: null,
                          width: 75.0,
                          height: 25.0,
                          child: GeneratedGenderWidget(),
                        ),
                        Positioned(
                          left: 34.0,
                          top: 500.0,
                          right: null,
                          bottom: null,
                          child: GroupButton(
                            isRadio: true,
                            direction: Axis.horizontal,
                            spacing: 20,
                            buttonHeight: 40,
                            selectedTextStyle: TextStyle(
                              fontFamily: "Comfortaa",
                            ),
                            unselectedTextStyle: TextStyle(
                              fontFamily: "Comfortaa",
                              color: Colors.black,
                            ),
                            buttonWidth: 70,
                            onSelected: (index, isSelected) => print('$index button is selected'),
                            buttons: [
                              "Male",
                              "Female",
                              "Others",
                            ],
                          ),
                        ),
                        // Positioned(
                        //   left: 139.0,
                        //   top: 504.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 79.0,
                        //   height: 20.0,
                        //   child: GeneratedGroup7880Widget(),
                        // ),
                        // Positioned(
                        //   left: 261.0,
                        //   top: 504.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 69.0,
                        //   height: 20.0,
                        //   child: GeneratedGroup7881Widget(),
                        // ),
                        Positioned(
                          left: 32.0,
                          top: 550.0,
                          right: null,
                          bottom: null,
                          width: 138.0,
                          height: 22.0,
                          child: GeneratedMaritalStatusWidget(),
                        ),
                        Positioned(
                          left: 34.0,
                          top: 584.0,
                          right: null,
                          bottom: null,
                          child: GroupButton(
                            isRadio: true,
                            direction: Axis.horizontal,
                            spacing: 10,
                            buttonHeight: 40,
                            selectedTextStyle: TextStyle(
                              fontFamily: "Comfortaa",
                            ),
                            unselectedTextStyle: TextStyle(
                              fontFamily: "Comfortaa",
                              color: Colors.black,
                            ),
                            buttonWidth: 95,
                            onSelected: (index, isSelected) => print('$index button is selected'),
                            buttons: [
                              "Married",
                              "Unmarried",
                              "Others",
                            ],
                          ),
                        ),
                        // Positioned(
                        //   left: 139.0,
                        //   top: 584.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 104.0,
                        //   height: 20.0,
                        //   child: GeneratedGroup7883Widget(),
                        // ),
                        // Positioned(
                        //   left: 261.0,
                        //   top: 584.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 69.0,
                        //   height: 20.0,
                        //   child: GeneratedGroup7884Widget(),
                        // ),
                        // Positioned(
                        //   left: 300.0,
                        //   top: 653.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 10.0,
                        //   height: 5.0,
                        //   child: GeneratedFrameWidget28(),
                        // ),
                        // Positioned(
                        //   left: 30.0,
                        //   top: 696.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 300.0,
                        //   height: 50.0,
                        //   child: GeneratedRectangle2869Widget1(),
                        // ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 708.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 93.0,
                        //   height: 31.0,
                        //   child: GeneratedOccupationWidget(),
                        // ),
                        // Positioned(
                        //   left: 300.0,
                        //   top: 719.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 10.0,
                        //   height: 5.0,
                        //   child: GeneratedFrameWidget29(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 975.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          child: FindDropdown(
                            items: [
                              "Occupation",
                              "Student",
                              "Employed",
                              "UnEmployed"
                            ],
                            label: "",
                            onChanged: (String item) => print(item),
                            selectedItem: "Country of Birth",
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 987.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 125.0,
                        //   height: 28.0,
                        //   child: GeneratedCountryofbirthWidget(),
                        // ),
                        // Positioned(
                        //   left: 300.0,
                        //   top: 998.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 10.0,
                        //   height: 5.0,
                        //   child: GeneratedFrameWidget30(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 1030.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          child: FindDropdown(
                            items: [
                              "Nationality",
                              "Student",
                              "Employed",
                              "UnEmployed"
                            ],
                            label: "",
                            onChanged: (String item) => print(item),
                            selectedItem: "Nationality",
                          ),
                        ),
                        // Positioned(
                        //   left: 50.0,
                        //   top: 1053.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 91.0,
                        //   height: 31.0,
                        //   child: GeneratedNationalityWidget(),
                        // ),
                        // Positioned(
                        //   left: 300.0,
                        //   top: 1064.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 10.0,
                        //   height: 5.0,
                        //   child: GeneratedFrameWidget31(),
                        // ),
                        Positioned(
                          left: 30.0,
                          top: 1265.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 51.0,
                          child: GeneratedGroup6607Widget6(),
                        ),
                        Positioned(
                          left: 30.0,
                          top: 845.0,
                          right: null,
                          bottom: null,
                          width: 300.0,
                          height: 50.0,
                          child: GeneratedGroup7886Widget(),
                        )
                      ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
