import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedFrameWidget45.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedAadharCard1111111111111111NamePrathamGoelMobileNo7082341.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedAsamehasbeensenttotheAuthorisedpersonWidget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedGroup6607Widget9.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedFrameWidget44.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedRectangle2913Widget1.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen21widget/generated/GeneratedGroup6610Widget4.dart';

/* Frame Screen 21
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 178.0,
                child: GeneratedFrameWidget44(),
              ),
              Positioned(
                left: 28.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 14.244000434875488,
                height: 15.072999954223633,
                child: GeneratedFrameWidget45(),
              ),
              Positioned(
                left: 28.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 181.0,
                child: GeneratedRectangle2913Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 68.0,
                child:
                    GeneratedAadharCard1111111111111111NamePrathamGoelMobileNo7082341(),
              ),
              Positioned(
                left: 58.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 51.0,
                child: GeneratedGroup6607Widget9(),
              ),
              Positioned(
                left: 89.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 182.14498901367188,
                height: 25.0,
                child: GeneratedGroup6610Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 54.0,
                child: GeneratedAsamehasbeensenttotheAuthorisedpersonWidget1(),
              )
            ]),
      ),
    ));
  }
}
