import 'package:flutter/material.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen4widget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen4widget/generated/GeneratedStep4Widget.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen4widget/generated/GeneratedAftersuccessfulverificationyourdocumentwillbesenttothep.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen4widget/generated/GeneratedLine1Widget3.dart';
import 'package:flutterapp/identt_20finalapp/generatedscreen4widget/generated/GeneratedGroup6606Widget2.dart';

/* Frame Screen 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 768.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 33.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 29.0,
                child: GeneratedStep4Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 72.0,
                child:
                    GeneratedAftersuccessfulverificationyourdocumentwillbesenttothep(),
              ),
              Positioned(
                left: 46.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 1.0,
                child: GeneratedLine1Widget3(),
              ),
              Positioned(
                left: 47.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 70.0,
                child: GeneratedGroup6606Widget2(),
              ),
              Positioned(
                left: 71.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 179.0,
                child: GeneratedImage3Widget(),
              )
            ]),
      ),
    ));
  }
}
